apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: gitops-demo
  # DISCOVERY MECHANISM: In a production setting, we use this label to bridge 
  # the gap between the application and the monitoring stack. Our ServiceMonitor 
  # is configured to "discover" any service with this specific label, allowing 
  # for zero-touch configuration as we scale.
  labels:
    app: flask-app
spec:
  # FINOPS & SECOPS CHOICE: Why ClusterIP?
  # 1. Security: Backend services should never be directly exposed to the public internet. 
  # 2. Cost: A LoadBalancer type triggers a cloud provider's API to provision a 
  #    dedicated (and expensive) resource. ClusterIP keeps traffic internal to 
  #    the cluster's private network, which is faster and free.
  type: ClusterIP
  selector:
    # This links the Service to our Flask pods managed by the Deployment.
    app: flask-app
  ports:
    # ABSTRACTION LAYER: We name this port 'http'. 
    # In a production setting, our monitoring tools (Prometheus) point to the 
    # name 'http' rather than the number '80'. This means we can change our 
    # network architecture later without breaking our dashboard.
  - name: http
    protocol: TCP
    port: 80        # The port the Service listens on inside the cluster.
    targetPort: 5000 # The actual port the Flask app is listening on in the container.